//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epidemic.API.Listings.Validators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epidemic.API.Listings.Validators.ValidationErrorMessages", typeof(ValidationErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The closing date must be after the creation date..
        /// </summary>
        internal static string ClosingDateBeforeEndDateNotValid {
            get {
                return ResourceManager.GetString("ClosingDateBeforeEndDateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified creation date is not valid..
        /// </summary>
        internal static string CreationDateNotValid {
            get {
                return ResourceManager.GetString("CreationDateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must contain at least one non-whitespace character..
        /// </summary>
        internal static string DescriptionCanNotBeEmpty {
            get {
                return ResourceManager.GetString("DescriptionCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.Empty is not a valid listing ID because it is non-unique. Use Guid.NewGuid() to generate a unique GUID..
        /// </summary>
        internal static string EmptyGuidIsNotAValidListingID {
            get {
                return ResourceManager.GetString("EmptyGuidIsNotAValidListingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A listing can only exist for up to {0} days..
        /// </summary>
        internal static string ListingExceedsMaxAgeFormat {
            get {
                return ResourceManager.GetString("ListingExceedsMaxAgeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The listing reference number is not valid..
        /// </summary>
        internal static string ListingReferenceNotValid {
            get {
                return ResourceManager.GetString("ListingReferenceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No listings exist with the specified reference number.
        /// </summary>
        internal static string ListingWithReferenceDoesNotExist {
            get {
                return ResourceManager.GetString("ListingWithReferenceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title must contain at least one non-whitespace character..
        /// </summary>
        internal static string TitleCanNotBeEmpty {
            get {
                return ResourceManager.GetString("TitleCanNotBeEmpty", resourceCulture);
            }
        }
    }
}
